apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "slurmtalks.fullname" . }}-config
  labels:
    {{- include "slurmtalks.labels" . | nindent 4 }}
data:
  # PostgreSQL
  POSTGRES_HOST: {{ .Values.backend.postgres.host | quote }}
  POSTGRES_PORT: {{ .Values.backend.postgres.port | quote }}
  MIGRATE_IN_CODE: {{ .Values.backend.postgres.migrateInCode | quote }}

  # Backend / Redis
  REDIS_ADDR: {{ .Values.backend.redis.addr | quote }}
  REDIS_DB: {{ .Values.backend.redis.db | quote }}

  # Frontend
  NEXT_PUBLIC_BACKEND_URL: {{ .Values.frontend.apiUrl | quote }}

  # Fake metrics
  SIMULATED_METRICS: {{ .Values.backend.simulatedMetrics.enabled | default false | quote }}
  SIMULATED_METRICS_INTERVAL: {{ .Values.backend.simulatedMetrics.interval | default "60s" | quote }}
  SIMULATED_METRICS_TWEETS: {{ .Values.backend.simulatedMetrics.tweets | default 10 | quote }}
  SIMULATED_METRICS_USERS: {{ .Values.backend.simulatedMetrics.users | default 10 | quote }}

