apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  labels:
    {{- include "slurmtalks.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.secret.postgres.db | quote }}
  POSTGRES_USER: {{ .Values.secret.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgres.password | quote }}
  JWT_SECRET_KEY: {{ .Values.secret.jwtSecretKey | quote }}
  REDIS_USER: {{ .Values.secret.redis.user | quote }}
  REDIS_PASSWORD: {{ .Values.secret.redis.password | quote }}